* Comprar bajo en sodio

Es complicado comer una dieta baja en sal.
Este documento contiene productos que:

- Podríamos pensar que tienen más cantidad de sal, pero en realidad no tienen tanta.
  (Intento comer cosas con menos de 1g sal/100g, preferiblemente menos de 0,5g.)
- Cosas que pese a no tener sal, son más sabrosas de lo que uno esperaría.

DISCLAIMER:
No soy médico ni nutricionista.
Contrastad todo lo que recomiendo aquí, que no son más que consejos y sugerencias sobre mis experiencias, sin ningún rigor médico.
El propósito de esta página es compartir ideas, no dar consejo médico/nutricional.

ATENCIÓN:
Listo específicamente el producto preciso y la cantidad de sal aplica solamente a ese producto.
Dentro de productos simiares, el contenido en sal puede variar muchísimo.
Prestad siempre atención al comprar para revisar la cantidad de sal, que puede no coincidir con la descrita aquí.
La sal no es la única fuente de sodio, revisad si lo que coméis lleva otras sustancias con sodio como el glutamato monosódico (o MSG).

** Recursos interesantes

- [[https://world.openfoodfacts.org][Open Food Facts]] tiene datos nutricionales sobre muchos productos.
  Sorprendentemente, he encontrado muchos productos buscando por código de barras.

** Productos

*** Quesos

- Alcampo - [[https://www.compraonline.alcampo.es/products/auchan-queso-arz%C3%BAa-ulloa-d-o-p-500-g-producto-alcampo/91158][AUCHAN Queso Arzúa Ulloa D.O.P. 500 g.]] - Sal 0,39/100g

  Este queso es el motivo principal para crear este documento.
  Este tipo de quesos parecen en general bajos en sal, y el de Alcampo tiene especialmente poca.
  Sin embargo, me gusta mucho (y me hace dudar que la información nutricional sea correcta).

  Los quesos tipo tetilla también tienen poca sal, pero más que este.

- Burratas - Sal; Mercadona 0,61/100g

  Las burratas también tienen poca sal, y pueden ayudar a dar algo de vida a algún plato.

- Mascarpone - Sal; Mercadona 0,11/100g

  El mascarpone puede servir para hacer más cremoso algún plato, sin añadir demasiada sal.

- Mercadona - Queso untar light de vaca Hacendado - Sal 0,75/100g

  El queso de untar light de Mercadona tiene bastante más sal que otros quesos apuntados aquí, pero menos que la mayoría de quesos de untar.
  Puede ser un capricho ocasional.

*** Pan

- Mercadona - Piquitos bajos en sal Hacendado - Sal 0,22/100g

  Para su bajo contenido en sal, los picos bajos en sal de Mercadona son muy sabrosos y pueden servir para picar.

*** Conservas

- Alcampo - [[https://www.compraonline.alcampo.es/products/producto-alcampo-h%C3%ADgado-de-bacalao-ahumado-115-g/649510][Hígado de bacalao ahumado 115 g.]] - Sal 0,54/100g

  El hígado de bacalao es graso, pero sabroso pese a no tener mucha sal.
  Puede servir para aderezar un plato.

- Atún en aceite bajo en sal - Sal; Calvo 0,16/100g, Mercadona 0,3/100g

  Aunque abuso un poco del atún bajo en sal, sirve para dar un poco de vida a muchos platos.
  Ojo, que la cantidad de sal puede variar mucho.

- Lomos de bonito en aceite - Sal; Miau 0,59/100g

  Los lomos de bonito en aceite, generalmente en tarros de cristal, llevan más sal que el atún en aceite bajo en sal, pero algunos no llevan mucho más y me parecen más sabrosos.
  Ojo, que la cantidad de sal puede variar mucho (por ejemplo el de Mercadona se va a 0,84/100g).

*** Platos preparados

- Litoral Fabada asturiana -30% sal y grasa - Sal 0,6/100g
- Tortilla de patata sin cebolla Auchan - Sal 0,91/100g
- Carrilera en salsa Carretilla - Sal 0.68/100g
- [[https://world.openfoodfacts.org/product/8436573552448/pizza-5-quesos-mamamasa][Pizza 5 quesos Mamamasa]] - Sal <0.1/100g

  Aunque los platos preparados suelen tener bastante sal, a veces alguno lleva menos de lo que parece.

*** Pasta

- Pasta rellena - Sal; Giovanni Rana ravioli costillas a la barbacoa 0,6g/100g

  Muchas pastas rellenas tienen bastante sal, pero al haber bastante variedad, a veces nos encontramos sorpresas.
  No es ideal comer pasta rellena sólo hervida, pero de esta manera podemos reducir nuestro consumo de sal.

*** Cereales

- Weetabix Crispy Minis Choco - Sal 0,16/100g

  De los mejores cereales con nutri-score A, y con menos sal que otros (e.g. los Choco Krispies de Kellogg's tienen 0,67g/100g de sal).
  (Nota: recientemente pasaron a tener nutri-score B, aunque la información nutricional no cambió.)
  Si queremos desayunar cereales, estos nos permiten ahorrar un poco de sodio.

*** Patatas

- Patatas microondas - Sal; Mercadona 0,015/100g

  Las patatas de microondas se preparan rápido y combinadas con otros productos, pueden arreglar una comida rápida.
  En general, suelen llevar muy poca sal y están buenas sin añadir más, aunque es recomendable aderezarlas con otro producto sin sal.

- Patatas prefritas congeladas - Sal; Mercadona Patatas prefritas Waffle fries Lambweston ultracongeladas 0,5/100g

  Muchas patatas prefritas congeladas no llevan mucha sal y se pueden comer perfectamente solas.

- Patatas fritas sin sal - Sal; Mercadona 0,011/100g

  Las patatas fritas sin sal están más buenas de lo que a priori cabría esperar, y pueden ser un aperitivo más que adecuado.

- Patatas Fritas en Aceite de Oliva "Arte Fritas" - Sal 0.5/100g

  Y no son frecuentes, pero algunas patatas fritas llevan menos sal que la mayoría.

- Preparados de patata - Sal; Mercadona patatas bravas con allioli y salsa picante 0,37/100g, Mercadona patatas con allioli 0,6/100g

  Aunque llevan más sal que otros productos de esta categoría, siguen teniendo no mucha sal y pueden ser otro aperitivo.

*** Arroces

- Arroz cocido basmati Sabroz Brillante - Sal 0,35/100g

  Los vasitos de arroz pueden variar bastante en sal, pero los Sabroz no llevan muchísima.
  Se pueden combinar con otros productos para arreglar una comida rápida.

*** Especias

- Curry

  Aunque en general no he encontrado especias que compensen comer sin sal, el curry es de lo que se acerca más.

*** Snacks

- Tortitas - Sal; Ecocesta 0,5/100g

  En general, las tortitas (de arroz, maíz, etc.) *no* son bajas en sal.
  Sin embargo, se pueden encontrar algunas con menos sal.
  En el Alcampo que uso, hay una sección con tortitas que todas tienen bastante sal, pero en la sección de alimentos dietéticos tienen las tortitas Ecocesta con menos sal.

- Tortolines chifles con sal - Sal 0,5/100g

  Estos chips de plátano tienen algo menos de sal que la mayoría de snacks salados que encontramos en el supermercado.

- Snacks y puffs Hero Eco - Sal 0-0,13/100g

  Hero tiene una línea de snacks para niños a partir de 8-10 meses.
  Son bastante reducidos en sal, así que son un poco sosos, pero tienen sabor y son crujientes.
