* Comprar bajo en sodio

Es complicado comer una dieta baja en sal.
Este documento contiene productos que:

- Podríamos pensar que tienen más cantidad de sal, pero en realidad no tienen tanta.
  (Intento comer cosas con menos de 1g sal/100g, preferiblemente menos de 0,5g.)
- Cosas que pese a no tener sal, son más sabrosas de lo que uno esperaría.

DISCLAIMER: no soy médico ni nutricionista, contrastad todo lo que recomiendo aquí y prestar siempre atención al comprar para revisar la cantidad de sal, que puede no coincidir con la descrita aquí.

** Productos

*** Quesos

- Alcampo - [[https://www.compraonline.alcampo.es/products/auchan-queso-arz%C3%BAa-ulloa-d-o-p-500-g-producto-alcampo/91158][AUCHAN Queso Arzúa Ulloa D.O.P. 500 g.]] - Sal 0,39/100g

  Este queso es el motivo principal para crear este documento.
  Este tipo de quesos parecen en general bajos en sal, y el de Alcampo tiene especialmente poca.
  Sin embargo, me gusta mucho (y me hace dudar que la información nutricional sea correcta).

  Los quesos tipo tetilla también tienen poca sal, pero más que este.

- Burratas - Sal; Mercadona 0,61/100g

  Las burratas también tienen poca sal, y pueden ayudar a dar algo de vida a algún plato.

- Mascarpone - Sal; Mercadona 0,11/100g

  El mascarpone puede servir para hacer más cremoso algún plato, sin añadir demasiada sal.

- Mercadona - Queso untar light de vaca Hacendado - Sal 0,75/100g

  El queso de untar light de Mercadona tiene bastante más sal que otros quesos apuntados aquí, pero menos que la mayoría de quesos de untar.
  Puede ser un capricho ocasional.

*** Pan

- Mercadona - Piquitos bajos en sal Hacendado - Sal 0,22/100g

  Para su bajo contenido en sal, los picos bajos en sal de Mercadona son muy sabrosos y pueden servir para picar.

*** Conservas

- Alcampo - [[https://www.compraonline.alcampo.es/products/producto-alcampo-h%C3%ADgado-de-bacalao-ahumado-115-g/649510][Hígado de bacalao ahumado 115 g.]] - Sal 0,54/100g

  El higado de bacalao es graso, pero sabroso pese a no tener mucha sal.
  Puede servir para aderezar un plato.

- Atun en aceite bajo en sal - Sal; Calvo 0,16/100g, Mercadona 0,30/100g

  Aunque abuso un poco del atún bajo en sal, sirve para dar un poco de vida a muchos platos.
  Ojo, que la cantidad de sal puede variar mucho.

- Lomos de bonito en aceite - Sal; Miau 0,59/100g

  Los lomos de bonito en aceite, generalmente en tarros de cristal, llevan más sal que el atún en aceite bajo en sal, pero algunos no llevan mucho más y me parecen más sabrosos.
  Ojo, que la cantidad de sal puede variar mucho (por ejemplo el de Mercadona se va a 0,84/100g).

*** Cereales

- Weetabix Crispy Minis Choco - Sal 0,16/100g

  De los mejores cerales con nutri-score A, y con menos sal que otros (e.g. los Choco Krispies de Kellogg's tienen 0,67g/100g de sal).
  Si queremos desayunar cereales, estos nos permiten ahorrar un poco de sodio.

*** Patatas

- Patatas microondas - Sal; Mercadona 0,015/100g

  Las patatas de microondas se preparan rápido y combinadas con otros productos, pueden arreglar una comida rápida.
  En general, suelen llevar muy poca sal y están buenas sin añadir más, aunque es recomendable aderezarlas con otro producto sin sal.

- Patatas prefritas congeladas - Sal; Mercadona Patatas prefritas Waffle fries Lambweston ultracongeladas 0,50g/100g

  Muchas patatas prefritas congeladas no llevan mucha sal y se pueden comer perfectamente solas.

- Patatas fritas sin sal - Sal; Mercadona 0,011/100g

  Las patatas fritas sin sal están más buenas de lo que a priori cabría esperar, y pueden ser un aperitivo más que adecuado.

- Preparados de patata - Sal; Mercadona patatas bravas con allioli y salsa picante 0,37/100g, Mercadona patatas con allioli 0,60/100g

  Aunque llevan más sal que otros productos de esta categoría, siguen teniendo no mucha sal y pueden ser otro aperitivo.

*** Especias

- Curry

  Aunque en general no he encontrado especias que compensen comer sin sal, el curry es de lo que se acerca más.
