---
- name: create DNS entries
  local_action:
    module: amazon.aws.route53
    zone: "{{ network.dns_zone }}"
    record: "{{ item }}"
    type: CNAME
    value: "{{ network.public_hostname }}"
    wait: true
    state: present
  loop: "{{ network.proxmox.proxy_hosts }}"
