---
- name: download template
  command: "pveam download local {{ flavors[proxmox.flavor].template }}_amd64.tar.xz"
  args:
    creates: "/var/lib/vz/template/cache/{{ flavors[proxmox.flavor].template }}_amd64.tar.xz"
  delegate_to: "{{ proxmox.host }}"
- name: create host
  command: >
    pct create {{ proxmox.id }} "/var/lib/vz/template/cache/{{ flavors[proxmox.flavor].template }}_amd64.tar.xz"
      --hostname {{ inventory_hostname }}
      --storage local-zfs
      -net0 name=eth0,bridge=vmbr0,ip=dhcp
      -onboot 1
      --unprivileged
      --password {{ ansible_password|trim }}
      --nameserver {{ hostvars[proxmox.host].network.self_internal_ip }}
      --ostype {{ flavors[proxmox.flavor].pct_ostype }}
  args:
    creates: "/etc/pve/lxc/{{ proxmox.id }}.conf"
  delegate_to: "{{ proxmox.host }}"
# https://bugzilla.proxmox.com/show_bug.cgi?id=4515
- name: set hosts
  copy:
    content: |
      127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

      {% if network is defined and network.ip is defined %}
      {{ network.ip }}  {{ inventory_hostname }} {{ inventory_hostname|regex_search('^[^.]*') }}
      {% endif %}
    dest: /rpool/data/subvol-{{ proxmox.id }}-disk-0/etc/hosts
  delegate_to: "{{ proxmox.host }}"
- name: prevent proxmox from manipulating hosts
  file:
    path: /etc/.pve-ignore.hosts
    state: touch
  delegate_to: "{{ proxmox.host }}"
- name: start host
  shell: "{ pct status {{ proxmox.id }} | grep running ; } || pct start {{ proxmox.id }}"
  delegate_to: "{{ proxmox.host }}"
- name: update packages to prevent automatic updates causing issues later. retry until network available
  command: pct exec {{ proxmox.id }} -- dnf update -y
  retries: 10
  delay: 1
  until: result.rc == 0
  register: result
  delegate_to: "{{ proxmox.host }}"
- name: install ssh
  command: pct exec {{ proxmox.id }} -- dnf install -y openssh-server
  delegate_to: "{{ proxmox.host }}"
- name: permit root password
  lineinfile:
    path: /rpool/data/subvol-{{ proxmox.id }}-disk-0/etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin yes"
  delegate_to: "{{ proxmox.host }}"
- name: enable ssh
  command: pct exec {{ proxmox.id }} -- systemctl enable --now sshd
  delegate_to: "{{ proxmox.host }}"
