apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/jcmoraisjr/haproxy-ingress/master/docs/haproxy-ingress.yaml
  - https://github.com/alexpdp7/talos-check/raw/main/manifest.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --watch-ingress-without-class
    target:
      kind: DaemonSet
      name: haproxy-ingress
      namespace: ingress-controller
  - patch: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: ingress-controller
        labels:
          pod-security.kubernetes.io/enforce: privileged
