apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.1/deploy/static/provider/cloud/deploy.yaml
  - https://github.com/alexpdp7/talos-check/raw/main/manifest.yaml
  - https://raw.githubusercontent.com/alexpdp7/alexpdp7/master/blog/k8s.yaml

patches:
  - patch: |-
      - op: add
        path: "/metadata/annotations/ingressclass.kubernetes.io~1is-default-class"
        value: true
    target:
      kind: IngressClass
      name: nginx
  - patch: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: ingress-nginx
        labels:
          pod-security.kubernetes.io/enforce: privileged
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ingress-nginx-controller
        namespace: ingress-nginx
      spec:
        template:
          spec:
            hostNetwork: true
