#!/bin/sh

set -ue

(
	cd arch-container-builder/
	./builder.py \
	             --package pkgfile \
		     --package ansible \
		     --package kubectl \
		     --package puppet \
		     --package sshpass \
		     --package git \
		     --package rust \
		     --package ipython \
		     --package maven \
		     --package python-pip \
		     --package python-pipx \
		     --package python-poetry \
		     --package python-jmespath \
		     --package python-kubernetes \
		     --package python-botocore \
		     --package python-boto3 \
		     --package certbot \
		     --package bitwarden-cli \
		     --package man-db \
		     --package isync \
		     --package soju \
                     --package libotr \
		     --package qemu-system-aarch64 \
		     --package qemu-system-arm-firmware \
		     --package qemu-img \
		     --package cdrtools \
		     --package emacs-nox \
		     --package mailutils \
		     --package xclip \
		     --package senpai \
		     --aur-package telegram-tdlib-purple-minimal-git \
		     --aur-package bitlbee-libpurple \
		     workstation
)
