#!/bin/sh

set -ue

(
	cd arch-container-builder/
	./builder.py \
		     --package ansible \
		     --package kubectl \
		     --package emacs-nox \
		     --package puppet \
		     --package sshpass \
		     --package git \
		     --package rust \
		     --package ipython \
		     --package python-pip \
		     --package python-pipx \
		     --package python-poetry \
		     --package python-jmespath \
		     --package python-kubernetes \
		     --package certbot \
		     --package bitwarden-cli \
		     --package xclip \
		     --package screen \
		     --package man-db \
		     --aur-package mu \
		     --aur-package talosctl \
		     workstation
)
