#!/bin/sh

set -uex

test -f ~/.cache/paperwmpaperwm.github.com.v145.shell-extension.zip || {
     wget https://extensions.gnome.org/extension-data/paperwmpaperwm.github.com.v145.shell-extension.zip -O ~/.cache/paperwmpaperwm.github.com.v145.shell-extension.zip
}

test -d ~/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com || {
    mkdir -p ~/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com
    cd ~/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com
    unzip ~/.cache/paperwmpaperwm.github.com.v145.shell-extension.zip
}

dconf load / <<EOF
[org/gnome/shell]
enabled-extensions=['paperwm@paperwm.github.com']
EOF
