---
- name: create lxc
  hosts: lxc
  gather_facts: false
  tags: create_lxc
  roles:
    - proxmox_create_lxc

- name: complete provision
  hosts: all,!k8s
  tags: puppet
  roles:
    - apply_puppet

- name: join ipa
  hosts: join_ipa
  tags: join_ipa
  roles:
    - join_ipa

- name: deploy ragent
  hosts: all,!k8s,!unmonitored
  tags: deploy_ragent
  roles:
    - deploy_ragent

- name: verify root mail
  hosts: all,!k8s
  tags: verify_root_mail
  roles:
    - verify_root_mail

- name: create k8s
  hosts: k8s
  tags: k8s
  gather_facts: false
  roles:
    - talos

- name: deploy ipsilon
  hosts: ipsilon
  tags: ipsilon
  roles:
    - deploy_ipsilon

- name: proxmox route 53
  hosts: proxmox
  tags: proxmox_route_53
  gather_facts: false
  roles:
    - proxmox_route_53

- name: deploy weight
  hosts: k8s-prod.h1.int.pdp7.net
  tags:
    - k8s
    - weight
  gather_facts: false
  roles:
    - role: zqxjkcrud
      vars:
        context: "admin@{{ talos_host.talos_cluster }}"
        definition: "{{ weight }}"

- name: deploy takahe
  hosts: k8s-prod.h1.int.pdp7.net
  tags:
    - k8s
    - takahe
  gather_facts: false
  roles:
    - role: takahe
      vars:
        context: "admin@{{ talos_host.talos_cluster }}"

- name: deploy coming-soon-rss
  hosts: k8s-prod.h1.int.pdp7.net
  tags:
    - k8s
    - coming-soon-rss
  gather_facts: false
  roles:
    - role: coming_soon_rss
      vars:
        context: "admin@{{ talos_host.talos_cluster }}"
        host: coming-soon-rss.k8s-prod.h1.int.pdp7.net
