---
- name: create lxc
  hosts: lxc
  gather_facts: false
  tags: create_lxc
  roles:
    - proxmox_create_lxc

- name: complete provision
  hosts: all
  tags: puppet
  roles:
    - apply_puppet

- name: join ipa
  hosts: join_ipa
  tags: join_ipa
  roles:
    - join_ipa

- name: verify root mail
  hosts: all
  tags: verify_root_mail
  roles:
    - verify_root_mail
