---
- name: create lxc
  hosts: lxc
  gather_facts: false
  tags: create_lxc
  roles:
    - proxmox_create_lxc

- name: complete provision
  hosts: all,!k8s
  tags: puppet
  roles:
    - apply_puppet

- name: join ipa
  hosts: join_ipa
  tags: join_ipa
  roles:
    - join_ipa

- name: deploy ragent
  hosts: all,!k8s
  tags: deploy_ragent
  roles:
    - deploy_ragent

- name: verify root mail
  hosts: all,!k8s
  tags: verify_root_mail
  roles:
    - verify_root_mail

- name: create k8s
  hosts: k8s
  tags: k8s
  gather_facts: false
  roles:
    - talos

- name: deploy ipsilon
  hosts: ipsilon
  tags: ipsilon
  roles:
    - deploy_ipsilon
