on:
  push:
    paths:
      - 'blog/**'
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: |
          cd blog/
          rustup toolchain install nightly --profile minimal
          podman login quay.io -u $BLOG_ROBOT_USERNAME -p $BLOG_ROBOT_TOKEN --authfile ~/docker-config
          chmod ugo+r ~/docker-config
          ./build.rs --docker-config ~/docker-config . quay.io/alexpdp7/blog:latest
        env:
          BLOG_ROBOT_USERNAME: ${{ vars.BLOG_ROBOT_USERNAME }}
          BLOG_ROBOT_TOKEN: ${{ secrets.BLOG_ROBOT_TOKEN }}
