on:
  push:
    paths:
      - 'personal_infra/containers/bitlbee-telegram/**'
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: |
          cd personal_infra/containers/bitlbee-telegram
          podman build . -t quay.io/alexpdp7/bitlbee-telegram:latest
          podman login -u="alexpdp7+github_workstation_builder" -p="$ROBOT_TOKEN" quay.io
          podman push quay.io/alexpdp7/bitlbee-telegram:latest
        env:
          ROBOT_TOKEN: ${{ secrets.ROBOT_TOKEN }}
